version: '3.8'
networks:
  mynetwork:
    driver: bridge
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9002:9000"
    image: linuxshakil/myflaskapp:dev
    networks:
      - mynetwork
  multistaged:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "9001:9000"
    image: linuxshakil/myflaskapp:prod
    networks:
      - mynetwork
  multistaged-replica:
    build:
      context: .
      dockerfile: Dockerfile.prod-replica
    ports:
      - "9000:9000"
    image: linuxshakil/myflaskapp-replica:v1
    networks:
      - mynetwork
  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    networks:
      - mynetwork